---
abstract: 'Warn of errors with stack backtrace and source context'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Carp-Source
provides:
  Carp::Source:
    file: lib/Carp/Source.pm
    version: 1.100820
  Carp::Source::Always:
    file: lib/Carp/Source/Always.pm
    version: 1.100820
  DB:
    file: lib/Carp/Source.pm
    version: 1.100820
requires:
  Carp: 0
  Class::Accessor::Constructor: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Term::ANSIColor: 0
  Test::Differences: 0
  Test::More: 0.88
  perl: 5.008
  utf8: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Carp-Source
  homepage: http://search.cpan.org/dist/Carp-Source/
  repository: http://github.com/hanekomu/Carp-Source
version: 1.100820
